server:
  port: 8080
  servlet:
    context-path: /dbook

spring:
  application:
    name: d-book-web
  datasource:
    url: "jdbc:mysql://localhost:3307/dbook"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB     # Giới hạn kích thước cho mỗi file tải lên
      max-request-size: 10MB   # Giới hạn kích thước cho toàn bộ yêu cầu
